title: Qisthi Alhazmi
description: A personal website of Qisthi Alhazmi Hidayaturrohman
theme: just-the-docs

url: https://alhazmi93.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
